//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubRenamer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubRenamer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确认信息 的本地化字符串。
        /// </summary>
        internal static string check_message {
            get {
                return ResourceManager.GetString("check_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行前请先备份字幕文件，以免识别错误导致字幕文件混乱\n撤销功能只能撤销上一次改名结果\n本消息只提示一次 的本地化字符串。
        /// </summary>
        internal static string check_message_string {
            get {
                return ResourceManager.GetString("check_message_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有操作记录 的本地化字符串。
        /// </summary>
        internal static string no_rename_record {
            get {
                return ResourceManager.GetString("no_rename_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不改名字幕文件 的本地化字符串。
        /// </summary>
        internal static string other_sub_filename {
            get {
                return ResourceManager.GetString("other_sub_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先获取文件 的本地化字符串。
        /// </summary>
        internal static string pls_load_file {
            get {
                return ResourceManager.GetString("pls_load_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改完成 的本地化字符串。
        /// </summary>
        internal static string rename_complete {
            get {
                return ResourceManager.GetString("rename_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分析失败，不要问为什么，就是失败了 的本地化字符串。
        /// </summary>
        internal static string resolve_fail {
            get {
                return ResourceManager.GetString("resolve_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销失败，重来吧 的本地化字符串。
        /// </summary>
        internal static string revoke_fail {
            get {
                return ResourceManager.GetString("revoke_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销成功 的本地化字符串。
        /// </summary>
        internal static string revoke_successed {
            get {
                return ResourceManager.GetString("revoke_successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则↓ 的本地化字符串。
        /// </summary>
        internal static string rgx_down {
            get {
                return ResourceManager.GetString("rgx_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则↑ 的本地化字符串。
        /// </summary>
        internal static string rgx_up {
            get {
                return ResourceManager.GetString("rgx_up", resourceCulture);
            }
        }
    }
}
